CURRENCY_USD = 1
CURRENCY_EUR = 2

CURRENCY_CHOICES = (
    (CURRENCY_USD, 'Dollar'),
    (CURRENCY_EUR, 'Euro'),
)

SOURCE_PRIVATBANK = 1
SOURCE_MONOBANK = 2
SOURCE_AVALBANK = 3

SOURCE_CHOICES = (
    (SOURCE_PRIVATBANK, 'PrivatBank'),
    (SOURCE_MONOBANK, 'MonoBank'),
    (SOURCE_AVALBANK, 'AvalBank'),
)
