# Generated by Django 3.2.4 on 2021-07-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_rate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('counter', models.PositiveBigIntegerField()),
            ],
        ),
    ]
