# Generated by Django 3.2.4 on 2021-07-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_urltracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URLTracker',
        ),
    ]
